version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
